name: actor
on:
  workflow_dispatch:
  push:

jobs:
  actor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
 
      - name: Dispay pull request status code
        run: echo "this workflow is started by ${{ github.actor }}" 

          
