name: solution pom.xml

on:
  pull_request:
    branches: [ feature ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        git branch
          echo "${{ github.run_id }}"
          echo "{{ github.run_number }}"
          echo "$GITHUB_RUN_NUMBER"echo "${{ github.server_url }}/${{ github.repository }}"
          echo ${{ env.URL_GITACTION }}
          echo ${GITHUB_REF##*/}
          echo ${{ github.actor }} 
          echo ${{ github.action_path }}
          echo ${{ github.action_ref }}
          echo ${{ github.action_repository	}}
          echo ${{ github.actor }}
          echo ${{ github.api_url }}
          echo ${{ github.base_ref }}
          echo ${{ github.env }}
          echo ${{ github.event }}
          echo ${{ github.event_name }}
          echo ${{ github.event_path }}
          echo ${{ github.graphql_url }}
          echo ${{ github.head_ref }}
          echo ${{ github.job }}
          echo ${{ github.ref }}
          echo ${{ github.ref_name }}
          echo ${{ github.ref_protected }}
          echo ${{ github.ref_type }}  #####
          echo ${{ github.path	 }}
          echo ${{ github.repository }}
          echo ${{ github.repository_owner }}
          echo ${{ github.repositoryUrl }}
          echo ${{ github.retention_days }}
          echo ${{ github.run_id }}
          echo ${{ github.run_number }}
          echo ${{ github.run_attempt }}
          echo ${{ github.server_url }}
          echo ${{ github.sha }}
          echo ${{ github.token }}
          echo ${{ github.workflow }}
          echo ${{ github.workspace }}
                
