name: Release
on:
  workflow_dispatch:
    inputs:
      Bumpversion:
        description: 'in above drop slect featue branch & below select semantic version bump'
        required: true
        default: 'warning' 
        type: choice
        options:
        - Major
        - Minor
        - Patch


jobs:
  Finalizing-next-tag-version:
    if: |
      github.ref_name != 'master' && github.ref_type == 'branch' && github.event_name == 'workflow_dispatch' 
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.LATEST_VERSION1 }}           
    steps:
      - uses: actions/checkout@v2
      - name: Fetch all tags
        run: |
          git fetch --all --tags
          git tag

      - name: Store the last tag
        run: |         
          echo "LAST_TAG=$(git tag | grep "v*.*.*" | tail -1)" >> $GITHUB_ENV          

      - name: Dispay the last tag
        run: |         
          echo "${{ env.LAST_TAG }}"

      - name: Store version
        shell: "bash"
        run: |-   
          echo "${{ env.LAST_TAG }}" 
          echo "MAJOR_NO=$(echo "${{ env.LAST_TAG }}" | cut -d'v' -f2 | cut -d'.' -f1)" >> $GITHUB_ENV
          echo "MINOR_NO=$(echo "${{ env.LAST_TAG }}" | cut -d'v' -f2 | cut -d'.' -f2)" >> $GITHUB_ENV
          echo "PATCH_NO=$(echo "${{ env.LAST_TAG }}" | cut -d'v' -f2 | cut -d'.' -f3)" >> $GITHUB_ENV   

      - name: Evaluating which version to bump
        run: |         
          echo "${{ env.MAJOR_NO }}" 
          echo "${{ env.MINOR_NO }}" 
          echo "${{ env.PATCH_NO }}"  
          if [[ ${{ github.event.inputs.Bumpversion }} == Major ]]; then echo "LATEST_TAG=v$((${{ env.MAJOR_NO }}+1)).0.0" >> $GITHUB_ENV; fi  
          if [[ ${{ github.event.inputs.Bumpversion }} == Minor ]]; then echo "LATEST_TAG=v${{ env.MAJOR_NO }}.$((${{ env.MAJOR_NO }}+1)).0" >> $GITHUB_ENV; fi  
          if [[ ${{ github.event.inputs.Bumpversion }} == Patch ]]; then echo "LATEST_TAG=v${{ env.MAJOR_NO }}.${{ env.MINOR_NO }}.$((${{ env.PATCH_NO }}+1))" >> $GITHUB_ENV; fi

      - name: Display the next tag version
        run: | 
          echo "${{ env.LATEST_TAG }}"
          echo "LATEST_VERSION=$(echo "${{ env.LATEST_TAG }}" | cut -d'v' -f2)" >> $GITHUB_ENV    
          echo "${{ env.LATEST_VERSION }}"

      - id: step1
        run: echo "::set-output name=LATEST_VERSION1::${{ env.LATEST_VERSION }}"                

      - name: Post to a Slack channel
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"${{ github.workflow }} ||| in ${{ github.event.repository.name }} repository  ||| in ${{ github.ref_name }} ${{ github.ref_type }} ||| is a ${{ job.status }} ||| click below url to see logs ||| ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}' ${{ secrets.SLACK_WEBHOOK }}


  merge-feature-to-master-branch:
    if: |
      github.ref_name != 'master' && github.ref_type == 'branch' && github.event_name == 'workflow_dispatch' 
    runs-on: ubuntu-latest
    needs: Finalizing-next-tag-version    
    steps:
      - uses: actions/checkout@v2

      - name: create a pull request
        run: gh pr create --title "Adding readme" --body "Testing pr from cli" --base master 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Store pull request number
        shell: "bash"
        run: |-  
          echo "PULLREQUEST_NO=$(gh pr view ${{ github.ref_name }} | head -10 | grep "number:" | cut -d':' -f2 | xargs echo -n)" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}     

      - name: Display pull request number
        run: echo "${{ env.PULLREQUEST_NO }}" 

      - name: Approve pull request 
        run: gh pr merge ${{ env.PULLREQUEST_NO }} --auto -m
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        

      - name: Post to a Slack channel
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"${{ github.workflow }} ||| in ${{ github.event.repository.name }} repository  ||| in ${{ github.ref_name }} ${{ github.ref_type }} ||| is a ${{ job.status }} ||| click below url to see logs ||| ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}' ${{ secrets.SLACK_WEBHOOK }}


  update-pomfile-in-master:
    if: |
      github.ref_name != 'master' && github.ref_type == 'branch' && github.event_name == 'workflow_dispatch' 
    runs-on: ubuntu-latest
    needs: [Finalizing-next-tag-version, merge-feature-to-master-branch]
    steps:
# checkout to branch
      - name: Checking out...
        uses: actions/checkout@v2
#Environment variables
      - name: Set GitHub_Env value
        run: |
          echo "JAVA_VERSION=$(cat ./.github/variable.txt | grep "JAVA_VERSION" | cut -d'=' -f2)" >> $GITHUB_ENV
# display java version 
      - name: Display GitHub_Env values
        run: |
          echo "The java version is  ${{ env.JAVA_VERSION }}"        
# install java in VM
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v2
        with:
          java-version: '8'                 # chnage after moving to actual                                                           
          distribution: 'adopt'

      - name: update & push to master
        run: |
          git config --global user.email "githubction@gmail.com"
          git config --global user.name "githubaction" 
          git pull --all
          git checkout master
          mvn versions:set -DnewVersion=${{needs.Finalizing-next-tag-version.outputs.output1}} -DprocessAllModules -DgenerateBackupPoms=false          
          git add .
          git commit -m "change pom.xml version to ${{needs.Finalizing-next-tag-version.outputs.output1}}"     
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git   

      - name: Post to a Slack channel
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"${{ github.workflow }} ||| in ${{ github.event.repository.name }} repository  ||| in ${{ github.ref_name }} ${{ github.ref_type }} ||| is a ${{ job.status }} ||| click below url to see logs ||| ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}' ${{ secrets.SLACK_WEBHOOK }}


  Automatic-tag:
    if: |
      github.ref_name != 'master' && github.ref_type == 'branch' && github.event_name == 'workflow_dispatch' 
    runs-on: ubuntu-latest
    needs: [Finalizing-next-tag-version, merge-feature-to-master-branch,update-pomfile-in-master]
    steps:
      - uses: actions/checkout@v2 
      - name: tag the master branch
        run: | 
          echo "v${{needs.Finalizing-next-tag-version.outputs.output1}}"
          git pull --all
          git checkout master          
          git tag v${{needs.Finalizing-next-tag-version.outputs.output1}}   
          git push origin v${{needs.Finalizing-next-tag-version.outputs.output1}}  
      

  Push-to-GCR:
#choose the OS in which you want to trigger the job 
    runs-on: ubuntu-latest
    needs: [Finalizing-next-tag-version, merge-feature-to-master-branch,update-pomfile-in-master,Automatic-tag]
    steps:
# checkout to branch
      - name: Checking out...
        uses: actions/checkout@v2
#Environment variables
      - name: Set GitHub_Env value
        run: |
          echo "HOSTNAME=$(cat ./.github/variable.txt | grep "HOSTNAME" | cut -d'=' -f2)" >> $GITHUB_ENV
          echo "PROJECT_ID=$(cat ./.github/variable.txt | grep "PROJECT_ID" | cut -d'=' -f2)" >> $GITHUB_ENV
          echo "MAVEN_GOAL=$(cat ./.github/variable.txt | grep "MAVEN_GOAL" | cut -d'=' -f2)" >> $GITHUB_ENV
          echo "SLACK_CHANNEL=$(cat ./.github/variable.txt | grep "SLACK_CHANNEL" | cut -d'=' -f2)" >> $GITHUB_ENV        
          echo "IMAGE_NAME=$(cat ./pom.xml | grep "artifactId" | cut -d'>' -f2 | cut -d'<' -f1 | head -1)" >> $GITHUB_ENV 
          echo "JAVA_VERSION=$(cat ./.github/variable.txt | grep "JAVA_VERSION" | cut -d'=' -f2)" >> $GITHUB_ENV

      - name: Display GitHub_Env values
        run: |
          echo "The hostname is ${{ env.HOSTNAME }}"
          echo "The Project id is ${{ env.PROJECT_ID }}" 
          echo "The maven goal is ${{ env.MAVEN_GOAL }}"    
          echo "job status will be sent to ${{ env.SLACK_CHANNEL }} slack channel"
          echo "The image name is ${{ env.IMAGE_NAME }}" 
          echo "The java version is  ${{ env.JAVA_VERSION }}"        
# install java in VM
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v2
        with:
          java-version: '${{ env.JAVA_VERSION }}'                                                                            
          distribution: 'adopt'  
# Build with Maven 
      - name: Build with Maven
        run: |
          git pull --all
          git checkout master
          mvn $MAVEN_GOAL             
# change path & build docker image          
      - name: build docker image
        run: |
          git pull --all
          git checkout master
          docker build -t $HOSTNAME/$PROJECT_ID/$IMAGE_NAME:$TAG_NAME .            
#Authentication to GCR      
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true              
#configure docker use Google cloud while pushing image
      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker --quiet
          gcloud auth configure-docker $env.PROJECT_ID --quiet         
# show all docker images in vm         
      - name: docker image
        run: docker images        
# push  docker image       
      - name: Docker Image to Container Registry (GCR)
        run: docker push $HOSTNAME/$PROJECT_ID/$IMAGE_NAME:${{ env.TAG_NAME }}
# send message to slack channel about job status
      - name: Post to a Slack channel
        if: always()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"${{ github.workflow }} ||| in ${{ github.event.repository.name }} repository  ||| in ${{ github.ref_name }} ${{ github.ref_type }} ||| is a ${{ job.status }} ||| click below url to see logs ||| ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}' ${{ secrets.SLACK_WEBHOOK }}
        
