name: Prod-CI
on: 
  push:
    branches: 
      - 'master'
    paths-ignore:
     - '.github/**'
     - '.gitignore'
     - '**.md'
jobs:
  upadte-pom.xml-in-master:
    if: |
      github.ref_name == 'master' && github.ref_type == 'branch' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
# checkout to branch
      - name: Checking out...
        uses: actions/checkout@v2

# install java in VM
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v2
        with:
          java-version: '${{ env.JAVA_VERSION }}'                                                                            
          distribution: 'adopt'

    - name: update & push to master
        run: |
          mvn versions:set -DnewVersion=bbbbbbbbbbbb -DprocessAllModules -DgenerateBackupPoms=false          
          git add .
          git commit -m "change pom.xml version to latest tag before merging"     
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          